### ISSUE TITLE
Motivate (or remove) $ prefix in helper functions like $url

### ISSUE THREAD

**Issue by tv42** [roxiness/routify.dev#172]
It would be nice if https://routify.dev/docs/helpers had a paragraph motivating the use of `$` in e.g. `$url`. For a moment I didn't connect it with the Svelte store concept, and thought you were using the prefix for stylistic reasons.

Something like this would help

> Identifiers shown here with a `$` prefix are [Svelte stores](link here). They are imported without the `$` prefix, and you can use the store API directly as such. Using the `$url` form makes Svelte do this automatically for you, and you can treat `$url` as a regular variable.

But even with that, the more action-oriented `$goto` feel weird as a store, as do `$beforeUrlChange`, `$afterPageLoad`, `$ready`. There's probably a very good implementation reason, I'm just reporting reader confusion at that moment.

**Comment by Wolfr** [comment]
Thanks for your feedback. I think they are reactive stores because they have to “react” to what is happening in the router but you are not supposed to use them likes stores (e.g. subscribe to them, update them). So to point out that they are stores might give people the wrong idea. What do you think @jakobrosenberg ? Does my comment make any sense?

**Comment by jakobrosenberg** [comment]
The helpers have different reasons to use the stores. Eg. the `ready` helper specifies when a page is ready. This can only be done by disabling the default behavior of the router, which would determine that the page is ready when it's loaded. In order to override the router, we have to notify it first, this is where the pseudo-store comes in. All stores are automatically subscribed at component initialization, so we put a script in the subscribe function which disables the router's own ready logic.

Running custom scripts in the subscribe function is something I believe all our pseudo-store helpers have in common. Most of them need to access Routify's context, which is only accessible at component initialization.

`beforeUrlChange` and `afterPageLoad` could possibly be rewritten as normal functions. I can't remember the motivation to use store logic for them.
