### ISSUE TITLE
examples/use-tailwind-css: Probably not the best advice?

### ISSUE THREAD

**Issue by tv42** [roxiness/routify.dev#173]
https://routify.dev/examples/use-tailwind-css says

> 4. Import Tailwind CSS to `src/App.svelte`
>
> ```
> <style  global>
>  /* purgecss start ignore */
>  @import 'tailwindcss/base';
> ```

and so on. When I asked about that on Discord (because it didn't work right), I was encouraged to *not* do that, and use external CSS. This should either get tested to really work on top https://github.com/roxiness/routify-starter with nothing but mechanically following the directions (or be a branch etc of the repo!), or changed to recommend the more traditional "keep CSS in CSS" style.

**Comment by Wolfr** [comment]
I believe I merged this example because we get a lot of Tailwind questions.  My thinking was: if this page helps people forward with Tailwind, that's great for me - less support, yay!

If it's seen as an official endorsement for Tailwind I wouldn't like that. I mean, people can use Tailwind, but I've personally written [page](https://johanronsse.be/2020/07/08/why-youll-probably-regret-using-tailwind/) after [page](https://johanronsse.be/2019/11/11/thoughts-on-tailwind-css/) why you probably shouldn't.

I cannot provide support for something I don't use myself. Perhaps we should mark this example as a community contribution on the website. I do think in general we want to provide some default way of handling CSS. The question then is: what is a good default?

**Comment by Wolfr** [comment]
I think we should add a box above the Tailwind article that this is a community contribution.

**Comment by ghostdevv** [comment]
This was done
